module.exports = {
  projects: [
    '<rootDir>/apps/main/web',
    '<rootDir>/apps/main/admin',
    '<rootDir>/apps/main/api',
    '<rootDir>/apps/discord/api',
    '<rootDir>/apps/discord/bot',
    '<rootDir>/apps/discord/web',
    '<rootDir>/apps/admin/api',
    '<rootDir>/libs/shared/passport-nrth-id',
    '<rootDir>/libs/shared/passport-internal',
    '<rootDir>/libs/shared/ui-react',
    '<rootDir>/apps/id/admin',
    '<rootDir>/apps/id/account',
    '<rootDir>/apps/id/api',
    '<rootDir>/libs/id/api/applications',
    '<rootDir>/libs/id/api/users',
    '<rootDir>/libs/id/api/groups',
    '<rootDir>/libs/id/api/connections',
    '<rootDir>/libs/id/api/templates',
    '<rootDir>/libs/id/api/auth',
    '<rootDir>/libs/main/api/donations',
    '<rootDir>/libs/main/api/status',
  ],
};
